name: Check For No Lint Errors
on: push

jobs:
  check-linting-(round-2):
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node_version: 22
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
